version: "3.3"

services:
  postgres-compose:
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data 
  
